### ISSUE TITLE
Notification of print fone

### ISSUE THREAD

**Issue by Eugeniusz-Gienek** [joseffallman/hass_flashforge#80]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/FlashForge/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

It would be great to send a notification to a smartphone HA app when print is really done. The thing is that one cannot rely on the status of print becoming 100% as for some reason this value is rounded and can be even 3-5 minutes earlier than the print is really done.

### Describe the solution you'd like

Provide a status of printing/sensor which can turn to "print done" or similar

### Describe alternatives you've considered

Status of print 100%

### Additional context

n/a

**Comment by joseffallman** [comment]
Trigger when temp is dropping to 0
This is the automation I'm using:
```
alias: Flashforge
description: Send notification that flashforge is done.
mode: single
triggers:
  - entity_id:
      - sensor.adventurer4_status
    from: BUILDING_FROM_SD
    to: READY
    enabled: false
    trigger: state
  - entity_id: sensor.adventurer4_extruder_target
    below: 1
    trigger: numeric_state
conditions:
  - condition: template
    value_template: "{{ trigger.from_state.state != \"unavailable\" }}"
actions:
  - data:
      message: "3D utskriften är klar. "
      title: Flashforge
      data:
        image: /api/camera_proxy/camera.adventurer4_camera
    action: notify.josefs_mobil
```
